codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
    patch:
      default:
        enabled: no # disable patch since it is noisy and not correct
        if_not_found: success
comment: true
